# Auto-generated by .github/workflows/release.yml on each tag. Do not edit by hand.
cask "ccswitch" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "39d3a6bb1f6267724e352abb0138ce693f81b30293d23f13ac1bf390bf3e71b5"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "94117d0533668bcc6e7d3f570a8d3e5c02ef30fdaac9e4bf992c7f5aa9d9b0db"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-apple-darwin.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "13c141ea051b53155a161a69d591170bd32420bb55e5acb487d746665802ee4d"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
    end
    on_intel do
      sha256 "74217ee0aecfce0de471f92f8183a3e94b12279c4d34ad085c06e93f6b9dd62f"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
    end
  end

  livecheck do
    url :url
    strategy :github_latest
  end

  name "ccswitch"
  desc "Switch between multiple Claude Code accounts"
  homepage "https://github.com/mysqto/ccswitch"

  binary "ccswitch"
end
