# Auto-generated by .github/workflows/release.yml on each tag. Do not edit by hand.
cask "ccswitch" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "eaac59162648b26d5d3feed164b5a6f6bd328236d2855389bd76092192aa4539"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-apple-darwin.tar.gz"
    end
    on_intel do
      sha256 "ca7855a32794b31a8f1a37e77068372658d5b868c7e631704ad7896f3e882435"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-apple-darwin.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "56ad1a75a3cc35dbcda49f9a93c9f902dde3f6c07db3533498cfad5bc0fc3c17"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
    end
    on_intel do
      sha256 "b4950d4ef1687b4684c4ce0e0df26fe3a780168e26eeb1dbe5905837d6c7ade1"
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
    end
  end

  livecheck do
    url :url
    strategy :github_latest
  end

  name "ccswitch"
  desc "Switch between multiple Claude Code accounts"
  homepage "https://github.com/mysqto/ccswitch"

  binary "ccswitch"
end
