# Auto-generated by .github/workflows/release.yml on each tag. Do not edit by hand.
# This committed copy is a template until the first release fills in real checksums.
class Ccswitch < Formula
  desc "Cross-shell switcher for multiple Claude Code accounts"
  homepage "https://github.com/mysqto/ccswitch"
  version "0.0.0"

  on_macos do
    on_arm do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  livecheck do
    url :url
    strategy :github_latest
  end

  def install
    bin.install "ccswitch"
    # Runs `ccswitch completions {bash,zsh,fish}` and installs each script so
    # tab-completion works immediately — the piece a cask can't do.
    generate_completions_from_executable(bin/"ccswitch", "completions")
  end

  test do
    assert_match "ccswitch", shell_output("#{bin}/ccswitch --help")
  end
end
