# Auto-generated by .github/workflows/release.yml on each tag. Do not edit by hand.
class Ccswitch < Formula
  desc "Cross-shell switcher for multiple Claude Code accounts"
  homepage "https://github.com/mysqto/ccswitch"
  version "0.1.4"

  on_macos do
    on_arm do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "49dfe1d4b3c2e292ece0c82a1720a3c39fdebab0deba61e2e2339d324089f606"
    end
    on_intel do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "0b3d5f4641d1227f42b8fbf3fbcf5e77ca113cd2ae1fd1f74588200a7c4911ff"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e1dfd96e149200bef9abc1420ad671d911b73106e83313effeb58e7e63bf319c"
    end
    on_intel do
      url "https://github.com/mysqto/ccswitch/releases/download/v#{version}/ccswitch-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5af532aa088734633b3c8a2285c1ece47211135cf099a1316d273d58dbfd1398"
    end
  end

  livecheck do
    url :url
    strategy :github_latest
  end

  def install
    bin.install "ccswitch"
    generate_completions_from_executable(bin/"ccswitch", "completions")
  end

  test do
    assert_match "ccswitch", shell_output("#{bin}/ccswitch --help")
  end
end
